### ISSUE TITLE
Enable Customization of API URL for Sandbox and Live Environments 

### ISSUE THREAD

**Issue by mdzihad89** [eijiotieno-official/flutter_mpesa#1]
**Issue Description:**

Currently, the URL in the code is hardcoded to the sandbox URL. To make this code more versatile and suitable for production use, it would be beneficial to allow users to configure the URL for different environments (sandbox and live).

**Comment by eijiotieno-official** [comment]
Thank you for the feedback, I'll update it by tomorrow
